structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnits.json?paging=false&filter=name:like:Sierra%20Leone&fields=name,id", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Tue, 09 Jun 2020 15:13:29 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0f145346ef434e2fa626ce3b81df5b849\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:13:29 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnits.json?paging=false&filter=name:like:Sierra%20Leone&fields=name,id", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:13:29 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0f145346ef434e2fa626ce3b81df5b849\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\"}]}"), 
    date = structure(1591715609, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.040608, namelookup = 2.1e-05, 
    connect = 2.3e-05, pretransfer = 5.2e-05, starttransfer = 0.049133, 
    total = 0.089763)), class = "response")
