structure(list(url = "https://play.dhis2.org/2.33.5/api/organisationUnitGroups.json?paging=false&filter=id:in:[gzcv65VyaGq,uYxK4wmcPqA,RXL3lPSK8oG]&fields=code,name,id", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Sat, 08 Aug 2020 23:20:55 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"04e62168981689e5206e421a698ccbd1d\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Sat, 08 Aug 2020 23:20:55 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            location = "https://play.dhis2.org/2.33.5/api/organisationUnitGroups.json?paging=false&filter=id:in:[gzcv65VyaGq,uYxK4wmcPqA,RXL3lPSK8oG]&fields=code,name,id", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx/1.17.10", date = "Sat, 08 Aug 2020 23:20:55 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "no-cache, private", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "W/\"04e62168981689e5206e421a698ccbd1d\"", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.5", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"code\":\"Chiefdom\",\"name\":\"Chiefdom\",\"id\":\"gzcv65VyaGq\"},{\"code\":\"CHP\",\"name\":\"CHP\",\"id\":\"uYxK4wmcPqA\"},{\"code\":\"Clinic\",\"name\":\"Clinic\",\"id\":\"RXL3lPSK8oG\"}]}"), 
    date = structure(1596928855, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.430481, namelookup = 0.000208, 
    connect = 0.144079, pretransfer = 0.29019, starttransfer = 0.590972, 
    total = 0.591153)), class = "response")
