structure(list(url = "https://play.dhis2.org/2.33.5/api/organisationUnits.json?paging=false&filter=organisationUnitGroups.name:eq:District&filter=children.id:in:[YuQRtpLP10I,fwH9ipvXde9]&fields=id,name,level", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Sat, 08 Aug 2020 20:36:00 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0af636ae6f981b76df4d3447e3f136500\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Sat, 08 Aug 2020 20:36:00 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            location = "https://play.dhis2.org/2.33.5/api/organisationUnits.json?paging=false&filter=organisationUnitGroups.name:eq:District&filter=children.id:in:[YuQRtpLP10I,fwH9ipvXde9]&fields=id,name,level", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx/1.17.10", date = "Sat, 08 Aug 2020 20:36:00 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "no-cache, private", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "W/\"0af636ae6f981b76df4d3447e3f136500\"", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.34.1", 
    "/2.33.5"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"level\":2,\"name\":\"Bo\",\"id\":\"O6uvpzGd5pu\"},{\"level\":2,\"name\":\"Bombali\",\"id\":\"fdc6uOvgoji\"}]}"), 
    date = structure(1596918960, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.430915, namelookup = 0.008022, 
    connect = 0.14712, pretransfer = 0.289996, starttransfer = 0.604051, 
    total = 0.604186)), class = "response")
