structure(list(url = "https://play.dhis2.org/2.33.5/api/categoryCombos.json?paging=false&filter=id:in:[m2jTvAj5kkm]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 20 Jul 2020 17:48:47 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"07ffe8ea4a311bd2f7d4d42aeeb4689f6\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 20 Jul 2020 17:48:47 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"07ffe8ea4a311bd2f7d4d42aeeb4689f6\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.5", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"categoryCombos\":[{\"name\":\"Births\",\"id\":\"m2jTvAj5kkm\"}]}"), 
    date = structure(1595267327, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000197, 
    connect = 0.000207, pretransfer = 0.000498, starttransfer = 0.155646, 
    total = 0.155776)), class = "response")
