structure(list(url = "https://play.dhis2.org/2.33.5/api/indicatorGroups.json?paging=false&filter=id:in:[oehv9EO3vP7]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 20 Jul 2020 17:48:58 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0d9715af44dbbf17fd360023e2a992359\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 20 Jul 2020 17:48:58 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0d9715af44dbbf17fd360023e2a992359\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.5", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"indicatorGroups\":[{\"name\":\"ANC\",\"id\":\"oehv9EO3vP7\"}]}"), 
    date = structure(1595267338, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000126, 
    connect = 0.000132, pretransfer = 0.000359, starttransfer = 0.240967, 
    total = 0.241037)), class = "response")
