structure(list(url = "https://play.dhis2.org/2.33.5/api/optionSets.json?paging=false&filter=id:in:[VQ2lai3OfVG]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 20 Jul 2020 17:49:03 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0e18bf8286de8375b423c49f3f1fef0a0\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 20 Jul 2020 17:49:03 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0e18bf8286de8375b423c49f3f1fef0a0\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.5", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"optionSets\":[{\"name\":\"Age category\",\"id\":\"VQ2lai3OfVG\"}]}"), 
    date = structure(1595267343, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5e-05, 
    connect = 5.3e-05, pretransfer = 0.000154, starttransfer = 0.156894, 
    total = 0.157007)), class = "response")
