structure(list(url = "https://play.dhis2.org/2.33.5/api/optionGroups.json?paging=false", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 20 Jul 2020 17:49:02 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-length` = "19", `cache-control` = "no-cache, private", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "\"015b63cd55676e9250e7182c7ea1e2391\"", 
        `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 20 Jul 2020 17:49:02 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `content-length` = "19", `cache-control` = "no-cache, private", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
            `x-content-type-options` = "nosniff", etag = "\"015b63cd55676e9250e7182c7ea1e2391\"", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.5", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"optionGroups\":[]}"), 
    date = structure(1595267342, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000174, 
    connect = 0.00018, pretransfer = 0.000484, starttransfer = 0.159504, 
    total = 0.159547)), class = "response")
