structure(list(url = "https://play.dhis2.org/2.33.5/api/organisationUnitGroups.json?paging=false&filter=name:in:[Country]&fields=name,organisationUnits[id,name,level,ancestors[id,name]]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Wed, 05 Aug 2020 21:51:19 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"032c2f1cf94e2687e3e4c5702807a0544\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Wed, 05 Aug 2020 21:51:19 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"032c2f1cf94e2687e3e4c5702807a0544\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.33.5", 
    "/2.34.1"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"Country\",\"organisationUnits\":[{\"level\":1,\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\",\"ancestors\":[]}]}]}"), 
    date = structure(1596664279, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 7.8e-05, 
    connect = 8.1e-05, pretransfer = 0.000177, starttransfer = 0.153088, 
    total = 0.153202)), class = "response")
