structure(list(url = "https://play.dhis2.org/2.33.4/api/dataElements.json?paging=false&filter=id:eq:FTRrcoaog83&fields=name,id", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Tue, 09 Jun 2020 14:45:43 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"010db96a7ee78df9e15395857cc08223b\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 14:45:43 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/dataElements.json?paging=false&filter=id:eq:FTRrcoaog83&fields=name,id", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 14:45:43 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"010db96a7ee78df9e15395857cc08223b\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"dataElements\":[{\"name\":\"Accute Flaccid Paralysis (Deaths < 5 yrs)\",\"id\":\"FTRrcoaog83\"}]}"), 
    date = structure(1591713943, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.154275, namelookup = 4.8e-05, 
    connect = 5.2e-05, pretransfer = 0.000137, starttransfer = 0.046456, 
    total = 0.200784)), class = "response")
