structure(list(url = "https://play.dhis2.org/2.33.4/api/dimensions.json?paging=false&filter=id:eq:gtuVl6NbXQV&fields=items[name,id]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Thu, 04 Jun 2020 08:19:01 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0c0261b7977c0e61e806e4fd6eb524370\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:01 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/dimensions.json?paging=false&filter=id:eq:gtuVl6NbXQV&fields=items[name,id]", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:01 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0c0261b7977c0e61e806e4fd6eb524370\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"dimensions\":[{\"items\":[{\"name\":\"Consumption\",\"id\":\"AdkHQiiJBB4\"},{\"name\":\"End Balance\",\"id\":\"xp1wtEkhBmV\"},{\"name\":\"Quantity to be ordered\",\"id\":\"gpK9r0M1RFZ\"}]}]}"), 
    date = structure(1591258741, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.033647, namelookup = 4.8e-05, 
    connect = 5.2e-05, pretransfer = 0.000134, starttransfer = 0.046164, 
    total = 0.079851)), class = "response")
