structure(list(url = "https://play.dhis2.org/2.33.4/api/dimensions.json?paging=false&filter=id:in:[yY2bQYqNt0o,gtuVl6NbXQV]&fields=name,id,code", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Thu, 04 Jun 2020 08:19:02 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0cf36c9c8a7fceb9abf3f0c28da39391c\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:02 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/dimensions.json?paging=false&filter=id:in:[yY2bQYqNt0o,gtuVl6NbXQV]&fields=name,id,code", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:02 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0cf36c9c8a7fceb9abf3f0c28da39391c\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"dimensions\":[{\"code\":\"PROJECT\",\"name\":\"Project\",\"id\":\"yY2bQYqNt0o\"},{\"code\":\"COMMODITIES\",\"name\":\"Commodities\",\"id\":\"gtuVl6NbXQV\"}]}"), 
    date = structure(1591258742, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.034278, namelookup = 5e-05, 
    connect = 5.4e-05, pretransfer = 0.000135, starttransfer = 0.045573, 
    total = 0.07991)), class = "response")
