structure(list(url = "https://play.dhis2.org/2.33.3/api/me.json?paging=false&fields=name", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Fri, 24 Apr 2020 07:44:41 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 24 Apr 2020 07:44:41 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.3/api/me.json?paging=false&fields=name", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 24 Apr 2020 07:44:41 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
            `x-content-type-options` = "nosniff", `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.3", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"name\":\"John Traore\"}"), 
    date = structure(1587714281, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.033009, namelookup = 2.8e-05, 
    connect = 2.9e-05, pretransfer = 6.1e-05, starttransfer = 0.041149, 
    total = 0.074198)), class = "response")
