structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=shortName:in:[Country,CHC]&fields=code,id,name,shortName", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 06 Jul 2020 19:47:51 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"00e78abdf3cfccdaab60fb4e7c17e6a21\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 06 Jul 2020 19:47:51 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=shortName:in:[Country,CHC]&fields=code,id,name,shortName", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx/1.17.10", date = "Mon, 06 Jul 2020 19:47:51 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "no-cache, private", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "W/\"00e78abdf3cfccdaab60fb4e7c17e6a21\"", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"code\":\"CHC\",\"name\":\"CHC\",\"id\":\"CXw2yu5fodb\",\"shortName\":\"CHC\"},{\"code\":\"Country\",\"name\":\"Country\",\"id\":\"RpbiCJpIYEj\",\"shortName\":\"Country\"}]}"), 
    date = structure(1594064871, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.345745, namelookup = 0.000119, 
    connect = 0.000125, pretransfer = 0.000275, starttransfer = 0.618326, 
    total = 0.618395)), class = "response")
