structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Thu, 04 Jun 2020 08:19:02 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"09a6092e47010594ce1e1cd30e8c72c61\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:02 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:02 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"09a6092e47010594ce1e1cd30e8c72c61\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"id\":\"CXw2yu5fodb\",\"displayName\":\"CHC\"},{\"id\":\"gzcv65VyaGq\",\"displayName\":\"Chiefdom\"},{\"id\":\"uYxK4wmcPqA\",\"displayName\":\"CHP\"},{\"id\":\"RXL3lPSK8oG\",\"displayName\":\"Clinic\"},{\"id\":\"RpbiCJpIYEj\",\"displayName\":\"Country\"},{\"id\":\"w1Atoz18PCL\",\"displayName\":\"District\"},{\"id\":\"nlX2VoouN63\",\"displayName\":\"Eastern Area\"},{\"id\":\"tDZVQ1WtwpA\",\"displayName\":\"Hospital\"},{\"id\":\"EYbopBOJWsW\",\"displayName\":\"MCHP\"},{\"id\":\"w0gFTTmsUcF\",\"displayName\":\"Mission\"},{\"id\":\"PVLOW4bCshG\",\"displayName\":\"NGO\"},{\"id\":\"J40PpdN4Wkk\",\"displayName\":\"Northern Area\"},{\"id\":\"MAs88nJc9nL\",\"displayName\":\"Private Clinic\"},{\"id\":\"oRVt7g429ZO\",\"displayName\":\"Public facilities\"},{\"id\":\"GGghZsfu7qV\",\"displayName\":\"Rural\"},{\"id\":\"jqBqIXoXpfy\",\"displayName\":\"Southern Area\"},{\"id\":\"f25dqv3Y7Z0\",\"displayName\":\"Urban\"},{\"id\":\"b0EsAxm8Nge\",\"displayName\":\"Western Area\"}]}"), 
    date = structure(1591258742, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.035543, namelookup = 3.5e-05, 
    connect = 3.7e-05, pretransfer = 9.1e-05, starttransfer = 0.042694, 
    total = 0.078285)), class = "response")
