structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=shortName:in:[Country,CHC,Country]&fields=code,id,name,shortName", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 06 Jul 2020 09:30:59 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"00e78abdf3cfccdaab60fb4e7c17e6a21\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 06 Jul 2020 09:30:59 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=shortName:in:[Country,CHC,Country]&fields=code,id,name,shortName", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 06 Jul 2020 09:30:59 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"00e78abdf3cfccdaab60fb4e7c17e6a21\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.33.4", 
    "/2.34.0"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"code\":\"CHC\",\"name\":\"CHC\",\"id\":\"CXw2yu5fodb\",\"shortName\":\"CHC\"},{\"code\":\"Country\",\"name\":\"Country\",\"id\":\"RpbiCJpIYEj\",\"shortName\":\"Country\"}]}"), 
    date = structure(1594027859, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.045794, namelookup = 6.7e-05, 
    connect = 7e-05, pretransfer = 0.000116, starttransfer = 0.057274, 
    total = 0.103093)), class = "response")
