structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnits.json?paging=false&filter=name:like:Baoma", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Thu, 04 Jun 2020 08:19:02 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0c05aab637e46f00cb98ef87bdc12f9f9\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:02 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnits.json?paging=false&filter=name:like:Baoma", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Thu, 04 Jun 2020 08:19:02 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0c05aab637e46f00cb98ef87bdc12f9f9\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"id\":\"vWbkYPRmKyS\",\"displayName\":\"Baoma\"},{\"id\":\"FLjwMPWLrL2\",\"displayName\":\"Baomahun CHC\"},{\"id\":\"Yj2ni275yPJ\",\"displayName\":\"Baoma (Koya) CHC\"},{\"id\":\"a1dP5m3Clw4\",\"displayName\":\"Baoma Kpenge CHP\"},{\"id\":\"TQ5DSmdliN7\",\"displayName\":\"Baoma (Luawa) MCHP\"},{\"id\":\"t52CJEyLhch\",\"displayName\":\"Baoma MCHP\"},{\"id\":\"Y8foq27WLti\",\"displayName\":\"Baoma Oil Mill CHC\"},{\"id\":\"x8SUTSsJoeO\",\"displayName\":\"Baoma-Peje CHP\"},{\"id\":\"jNb63DIHuwU\",\"displayName\":\"Baoma Station CHP\"},{\"id\":\"KfUCAQoOIae\",\"displayName\":\"Pelewahun (Baoma) MCHP\"}]}"), 
    date = structure(1591258742, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.034157, namelookup = 3.9e-05, 
    connect = 4.2e-05, pretransfer = 0.000108, starttransfer = 0.045264, 
    total = 0.079482)), class = "response")
