structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&fields=name,id", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Tue, 09 Jun 2020 15:06:22 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"05c971d1e665f8c65b7cd0ca38a2b65c8\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:06:22 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&fields=name,id", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:06:22 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"05c971d1e665f8c65b7cd0ca38a2b65c8\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"CHC\",\"id\":\"CXw2yu5fodb\"},{\"name\":\"Chiefdom\",\"id\":\"gzcv65VyaGq\"},{\"name\":\"CHP\",\"id\":\"uYxK4wmcPqA\"},{\"name\":\"Clinic\",\"id\":\"RXL3lPSK8oG\"},{\"name\":\"Country\",\"id\":\"RpbiCJpIYEj\"},{\"name\":\"District\",\"id\":\"w1Atoz18PCL\"},{\"name\":\"Eastern Area\",\"id\":\"nlX2VoouN63\"},{\"name\":\"Hospital\",\"id\":\"tDZVQ1WtwpA\"},{\"name\":\"MCHP\",\"id\":\"EYbopBOJWsW\"},{\"name\":\"Mission\",\"id\":\"w0gFTTmsUcF\"},{\"name\":\"NGO\",\"id\":\"PVLOW4bCshG\"},{\"name\":\"Northern Area\",\"id\":\"J40PpdN4Wkk\"},{\"name\":\"Private Clinic\",\"id\":\"MAs88nJc9nL\"},{\"name\":\"Public facilities\",\"id\":\"oRVt7g429ZO\"},{\"name\":\"Rural\",\"id\":\"GGghZsfu7qV\"},{\"name\":\"Southern Area\",\"id\":\"jqBqIXoXpfy\"},{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"},{\"name\":\"Western Area\",\"id\":\"b0EsAxm8Nge\"}]}"), 
    date = structure(1591715182, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.283242, namelookup = 4.4e-05, 
    connect = 4.7e-05, pretransfer = 0.000121, starttransfer = 0.055864, 
    total = 0.339174)), class = "response")
