structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&fields=name", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Fri, 12 Jun 2020 10:19:46 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"01d48ded437add8c8055f6a2f32115e05\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 12 Jun 2020 10:19:46 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&fields=name", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 12 Jun 2020 10:19:46 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"01d48ded437add8c8055f6a2f32115e05\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"CHC\"},{\"name\":\"Chiefdom\"},{\"name\":\"CHP\"},{\"name\":\"Clinic\"},{\"name\":\"Country\"},{\"name\":\"District\"},{\"name\":\"Eastern Area\"},{\"name\":\"Hospital\"},{\"name\":\"MCHP\"},{\"name\":\"Mission\"},{\"name\":\"NGO\"},{\"name\":\"Northern Area\"},{\"name\":\"Private Clinic\"},{\"name\":\"Public facilities\"},{\"name\":\"Rural\"},{\"name\":\"Southern Area\"},{\"name\":\"Urban\"},{\"name\":\"Western Area\"}]}"), 
    date = structure(1591957186, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.245617, namelookup = 3.3e-05, 
    connect = 3.5e-05, pretransfer = 8.7e-05, starttransfer = 0.043318, 
    total = 0.289002)), class = "response")
