structure(list(url = "https://play.dhis2.org/2.33.6/api/organisationUnitGroups.json?paging=false&filter=name:in:[Country,Facility]&fields=name,organisationUnits[id]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Sat, 03 Oct 2020 19:11:24 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"044a49e2123cf15a90833a134179d7f6b\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Sat, 03 Oct 2020 19:11:24 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            location = "https://play.dhis2.org/2.33.6/api/organisationUnitGroups.json?paging=false&filter=name:in:[Country,Facility]&fields=name,organisationUnits[id]", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx/1.17.10", date = "Sat, 03 Oct 2020 19:11:24 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "no-cache, private", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "W/\"044a49e2123cf15a90833a134179d7f6b\"", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.34.1", 
    "/2.33.6"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"Country\",\"organisationUnits\":[{\"id\":\"ImspTQPwCqd\"}]}]}"), 
    date = structure(1601752284, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.436976, namelookup = 0.000118, 
    connect = 0.14616, pretransfer = 0.294328, starttransfer = 0.579836, 
    total = 0.581334)), class = "response")
