structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnits.json?paging=false&filter=name:like:Baoma&fields=name,id", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Tue, 09 Jun 2020 15:10:09 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0643df7cc7e37d435e0334d85694b1f89\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:10:09 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnits.json?paging=false&filter=name:like:Baoma&fields=name,id", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:10:09 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0643df7cc7e37d435e0334d85694b1f89\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"name\":\"Baoma\",\"id\":\"vWbkYPRmKyS\"},{\"name\":\"Baomahun CHC\",\"id\":\"FLjwMPWLrL2\"},{\"name\":\"Baoma (Koya) CHC\",\"id\":\"Yj2ni275yPJ\"},{\"name\":\"Baoma Kpenge CHP\",\"id\":\"a1dP5m3Clw4\"},{\"name\":\"Baoma (Luawa) MCHP\",\"id\":\"TQ5DSmdliN7\"},{\"name\":\"Baoma MCHP\",\"id\":\"t52CJEyLhch\"},{\"name\":\"Baoma Oil Mill CHC\",\"id\":\"Y8foq27WLti\"},{\"name\":\"Baoma-Peje CHP\",\"id\":\"x8SUTSsJoeO\"},{\"name\":\"Baoma Station CHP\",\"id\":\"jNb63DIHuwU\"},{\"name\":\"Pelewahun (Baoma) MCHP\",\"id\":\"KfUCAQoOIae\"}]}"), 
    date = structure(1591715409, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.133221, namelookup = 2e-05, 
    connect = 2.2e-05, pretransfer = 5.1e-05, starttransfer = 0.046033, 
    total = 0.179315)), class = "response")
