structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=id:in:[w1Atoz18PCL,CXw2yu5fodb]&fields=name", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Tue, 09 Jun 2020 15:27:40 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"032c52533d5041fdf9867049b024a7dba\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:27:40 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=id:in:[w1Atoz18PCL,CXw2yu5fodb]&fields=name", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Tue, 09 Jun 2020 15:27:40 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"032c52533d5041fdf9867049b024a7dba\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"CHC\"},{\"name\":\"District\"}]}"), 
    date = structure(1591716460, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.1483, namelookup = 2e-05, 
    connect = 2.2e-05, pretransfer = 5.3e-05, starttransfer = 0.043879, 
    total = 0.192231)), class = "response")
