structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=code:in:[CHC]&fields=code,name,id", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Thu, 02 Jul 2020 19:21:29 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"07d72dbc3dd640f9925149de2f1c7b2ee\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Thu, 02 Jul 2020 19:21:28 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=code:in:[CHC]&fields=code,name,id", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx/1.17.10", date = "Thu, 02 Jul 2020 19:21:29 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "no-cache, private", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "W/\"07d72dbc3dd640f9925149de2f1c7b2ee\"", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"code\":\"CHC\",\"name\":\"CHC\",\"id\":\"CXw2yu5fodb\"}]}"), 
    date = structure(1593717689, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.166896, namelookup = 0.000159, 
    connect = 0.000164, pretransfer = 0.000323, starttransfer = 0.337277, 
    total = 0.337407)), class = "response")
