structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroupSets.json?paging=false&fields=organisationUnitGroups[name]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Fri, 12 Jun 2020 11:08:14 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0f390a2465eb2e4c56987a6414d802740\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 12 Jun 2020 11:08:14 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroupSets.json?paging=false&fields=organisationUnitGroups[name]", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 12 Jun 2020 11:08:14 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0f390a2465eb2e4c56987a6414d802740\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroupSets\":[{\"organisationUnitGroups\":[{\"name\":\"Eastern Area\"},{\"name\":\"Northern Area\"},{\"name\":\"Southern Area\"},{\"name\":\"Western Area\"}]},{\"organisationUnitGroups\":[{\"name\":\"NGO\"},{\"name\":\"Public facilities\"},{\"name\":\"Private Clinic\"},{\"name\":\"Mission\"}]},{\"organisationUnitGroups\":[{\"name\":\"CHP\"},{\"name\":\"CHC\"},{\"name\":\"MCHP\"},{\"name\":\"Clinic\"},{\"name\":\"Hospital\"}]},{\"organisationUnitGroups\":[{\"name\":\"Urban\"},{\"name\":\"Rural\"}]}]}"), 
    date = structure(1591960094, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.126347, namelookup = 2.7e-05, 
    connect = 3e-05, pretransfer = 7e-05, starttransfer = 0.053291, 
    total = 0.179707)), class = "response")
