structure(list(url = "https://play.dhis2.org/2.36.3/api/dataStore/metabase/foo", 
    status_code = 404L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 16 Aug 2021 09:33:16 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 16 Aug 2021 09:33:16 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.36.3", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"httpStatus\":\"Not Found\",\"httpStatusCode\":404,\"status\":\"ERROR\",\"message\":\"The key 'foo' was not found in the namespace 'metabase'.\"}"), 
    date = structure(1629106396, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.8e-05, pretransfer = 8.8e-05, starttransfer = 0.064321, 
    total = 0.064377)), class = "response")
