structure(list(url = "https://play.dhis2.org/2.34.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=name,organisationUnitGroups[name]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Wed, 05 Aug 2020 12:05:59 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"089654162c953274c31d5cc7ca52af60d\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Wed, 05 Aug 2020 12:05:59 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.34.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=name,organisationUnitGroups[name]", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Wed, 05 Aug 2020 12:05:59 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"089654162c953274c31d5cc7ca52af60d\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.34.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"name\":\"Adonkia CHP\",\"organisationUnitGroups\":[{\"name\":\"Urban\"}]},{\"name\":\"Afro Arab Clinic\",\"organisationUnitGroups\":[{\"name\":\"Urban\"},{\"name\":\"Clinic\"}]}]}"), 
    date = structure(1596629159, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.042075, namelookup = 3.1e-05, 
    connect = 3.2e-05, pretransfer = 6.9e-05, starttransfer = 0.05752, 
    total = 0.09963)), class = "response")
