structure(list(url = "https://play.dhis2.org/2.34.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=name,organisationUnitGroups[name,id]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Wed, 05 Aug 2020 13:48:10 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"01ace375f252c87a07707190dbcc09af2\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Wed, 05 Aug 2020 13:48:10 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.34.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=name,organisationUnitGroups[name,id]", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Wed, 05 Aug 2020 13:48:10 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"01ace375f252c87a07707190dbcc09af2\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.34.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"name\":\"Adonkia CHP\",\"organisationUnitGroups\":[{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"}]},{\"name\":\"Afro Arab Clinic\",\"organisationUnitGroups\":[{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"},{\"name\":\"Clinic\",\"id\":\"RXL3lPSK8oG\"}]}]}"), 
    date = structure(1596635290, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.197663, namelookup = 5.3e-05, 
    connect = 5.8e-05, pretransfer = 0.000132, starttransfer = 0.049577, 
    total = 0.247313)), class = "response")
