structure(list(url = "https://play.dhis2.org/2.34.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=organisationUnitGroups[name,id],ancestors[name,id]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Fri, 07 Aug 2020 11:51:12 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0038352dacfb1fd2976de56fc961278d8\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Fri, 07 Aug 2020 11:51:12 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.34.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=organisationUnitGroups[name,id],ancestors[name,id]", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Fri, 07 Aug 2020 11:51:12 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0038352dacfb1fd2976de56fc961278d8\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.34.1", 
    "/2.33.5"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"organisationUnitGroups\":[{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"}],\"ancestors\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\"},{\"name\":\"Western Area\",\"id\":\"at6UHUQatSo\"},{\"name\":\"Rural Western Area\",\"id\":\"qtr8GGlm4gg\"}]},{\"organisationUnitGroups\":[{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"},{\"name\":\"Clinic\",\"id\":\"RXL3lPSK8oG\"}],\"ancestors\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\"},{\"name\":\"Western Area\",\"id\":\"at6UHUQatSo\"},{\"name\":\"Rural Western Area\",\"id\":\"qtr8GGlm4gg\"}]}]}"), 
    date = structure(1596801072, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.179939, namelookup = 5.1e-05, 
    connect = 5.4e-05, pretransfer = 0.000124, starttransfer = 0.059754, 
    total = 0.239759)), class = "response")
