structure(list(url = "https://play.dhis2.org/2.33.3/api/indicators/ReUHfIn0pTQ.json?paging=false", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Fri, 24 Apr 2020 09:40:58 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0b28c29a894fdac9f5e11f34d9df105e0\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 24 Apr 2020 09:40:58 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.3/api/indicators/ReUHfIn0pTQ.json?paging=false", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 24 Apr 2020 09:40:58 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0b28c29a894fdac9f5e11f34d9df105e0\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.3", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"code\":\"IN_52462\",\"lastUpdated\":\"2013-03-21T11:17:44.926\",\"id\":\"ReUHfIn0pTQ\",\"href\":\"https://play.dhis2.org/2.33.3/api/indicators/ReUHfIn0pTQ\",\"created\":\"2012-11-05T09:16:29.054\",\"name\":\"ANC 1-3 Dropout Rate\",\"shortName\":\"ANC 1-3 Dropout Rate\",\"displayName\":\"ANC 1-3 Dropout Rate\",\"publicAccess\":\"rw------\",\"description\":\"Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.\",\"displayShortName\":\"ANC 1-3 Dropout Rate\",\"externalAccess\":false,\"denominatorDescription\":\"Total 1st ANC visits\",\"numeratorDescription\":\"ANC1-ANC3\",\"displayDescription\":\"Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.\",\"dimensionItem\":\"ReUHfIn0pTQ\",\"url\":\"\",\"numerator\":\"#{fbfJHSPpUQD.pq2XI5kz2BY}+#{fbfJHSPpUQD.PT59n8BQbqM}-#{Jtf34kNZhzP.pq2XI5kz2BY}-#{Jtf34kNZhzP.PT59n8BQbqM}\",\"denominator\":\"#{fbfJHSPpUQD.pq2XI5kz2BY}+#{fbfJHSPpUQD.PT59n8BQbqM}\",\"annualized\":false,\"favorite\":false,\"dimensionItemType\":\"INDICATOR\",\"access\":{\"read\":true,\"update\":true,\"externalize\":false,\"delete\":true,\"write\":true,\"manage\":true},\"indicatorType\":{\"id\":\"bWuNrMHEoZ0\"},\"user\":{\"id\":\"GOLswS44mh8\"},\"favorites\":[],\"translations\":[{\"property\":\"SHORT_NAME\",\"locale\":\"fr\",\"value\":\" Taux d'abandon d'ANC 1-3\"},{\"property\":\"NAME\",\"locale\":\"fr\",\"value\":\" Taux d'abandon d'ANC 1-3\"},{\"property\":\"NAME\",\"locale\":\"en_GB\",\"value\":\"ANC Dropout Rate\"},{\"property\":\"SHORT_NAME\",\"locale\":\"en_GB\",\"value\":\"ANC Dropout Rate\"},{\"property\":\"DESCRIPTION\",\"locale\":\"en_GB\",\"value\":\"Indicates the percentage of clients dropping out between the 1st and the 3rd ANC visit. Calculated as the difference between ANC1 and ANC3 by the ANC 1 visits.\"}],\"userGroupAccesses\":[],\"attributeValues\":[],\"indicatorGroups\":[{\"id\":\"oehv9EO3vP7\"},{\"id\":\"YTeRMLGtger\"}],\"userAccesses\":[],\"dataSets\":[],\"legendSets\":[]}"), 
    date = structure(1587721258, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.128954, namelookup = 4.5e-05, 
    connect = 4.7e-05, pretransfer = 0.000108, starttransfer = 0.049839, 
    total = 0.178872)), class = "response")
