structure(list(url = "https://play.dhis2.org/2.35.0/api/sqlViews.json?paging=false", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Wed, 04 Nov 2020 20:02:05 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"0fd3c780b243b567fe9dc81dc8ed46f2b\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Wed, 04 Nov 2020 20:02:05 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            location = "https://play.dhis2.org/2.35.0/api/sqlViews.json?paging=false", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx/1.17.10", date = "Wed, 04 Nov 2020 20:02:05 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "no-cache, private", 
        etag = "W/\"0fd3c780b243b567fe9dc81dc8ed46f2b\"", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.35.0", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"sqlViews\":[{\"id\":\"QAlOivHBY3a\",\"displayName\":\"Category option combo overview\"},{\"id\":\"YOaOY605rzh\",\"displayName\":\"Code list category option combos\"},{\"id\":\"GCZ01m3pIRd\",\"displayName\":\"Code list data elements\"},{\"id\":\"cOfhJIFGqhP\",\"displayName\":\"Code list data sets\"},{\"id\":\"w3UxFykyHFy\",\"displayName\":\"Code list organisation units\"},{\"id\":\"qMYMT0iUGkG\",\"displayName\":\"Data element by value type\"},{\"id\":\"tw3A6ZXOdbA\",\"displayName\":\"Data elements\"},{\"id\":\"NdbAwXmwE8N\",\"displayName\":\"Data set approval\"},{\"id\":\"ITDzVWfa8DN\",\"displayName\":\"Datavalue\"},{\"id\":\"dI68mLkP1wN\",\"displayName\":\"Facility Overview\"}]}"), 
    date = structure(1604520125, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.437275, namelookup = 0.007991, 
    connect = 0.146064, pretransfer = 0.296321, starttransfer = 0.584479, 
    total = 0.584597)), class = "response")
