structure(list(url = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=name:in:[CHP,Rural]&fields=name,id,code", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.9", 
        date = "Fri, 12 Jun 2020 14:43:47 GMT", `content-type` = "application/json;charset=UTF-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"08624c6d64d6e37f6aa2106524e8ac59b\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 12 Jun 2020 14:43:47 GMT", 
            `content-type` = "text/html", `content-length` = "145", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.4/api/organisationUnitGroups.json?paging=false&filter=name:in:[CHP,Rural]&fields=name,id,code", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.9", date = "Fri, 12 Jun 2020 14:43:47 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache, private", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"08624c6d64d6e37f6aa2106524e8ac59b\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.4", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"code\":\"CHP\",\"name\":\"CHP\",\"id\":\"uYxK4wmcPqA\"},{\"name\":\"Rural\",\"id\":\"GGghZsfu7qV\"}]}"), 
    date = structure(1591973027, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.127747, namelookup = 4.7e-05, 
    connect = 5.1e-05, pretransfer = 0.000127, starttransfer = 0.04565, 
    total = 0.17345)), class = "response")
