structure(list(url = "https://play.dhis2.org/2.37.2/api/me", 
    status_code = 401L, headers = structure(list(server = "nginx", 
        date = "Thu, 20 Jan 2022 17:44:29 GMT", `content-type` = "application/xml;charset=UTF-8", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Thu, 20 Jan 2022 17:44:29 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.37/api/me"), class = c("insensitive", 
        "list"))), list(status = 302L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Thu, 20 Jan 2022 17:44:29 GMT", 
        `content-type` = "text/html", `content-length` = "138", 
        location = "https://play.dhis2.org/2.37.2/api/me", `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
    "list"))), list(status = 401L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Thu, 20 Jan 2022 17:44:29 GMT", 
        `content-type` = "application/xml;charset=UTF-8", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<webMessage xmlns=\"http://dhis2.org/schema/dxf/2.0\" httpStatus=\"Unauthorized\" httpStatusCode=\"401\" status=\"ERROR\"><message>Unauthorized</message></webMessage>"), 
    date = structure(1642700669, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.260653, namelookup = 7.7e-05, 
    connect = 8.2e-05, pretransfer = 0.000231, starttransfer = 0.46598, 
    total = 0.466084)), class = "response")
