structure(list(url = "https://play.dhis2.org/40.0.1/api/analytics.json?paging=false&dimension=dx:fbfJHSPpUQD;cYeuwXTCPkU&dimension=pe:201601&dimension=ou:O6uvpzGd5pu;lc3eMKXaEfw&dimension=co&outputIdScheme=UID", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 13:36:45 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "max-age=1209600, public", etag = "W/\"0cb83b782673a177875c8e38dc40bedd7\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 13:36:45 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/analytics.json?paging=false&dimension=dx:fbfJHSPpUQD;cYeuwXTCPkU&dimension=pe:201601&dimension=ou:O6uvpzGd5pu;lc3eMKXaEfw&dimension=co&outputIdScheme=UID"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 13:36:45 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "max-age=1209600, public", etag = "W/\"0cb83b782673a177875c8e38dc40bedd7\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"headers\":[{\"name\":\"dx\",\"column\":\"Data\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"co\",\"column\":\"Category option combo\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"pe\",\"column\":\"Period\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"ou\",\"column\":\"Organisation unit\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"value\",\"column\":\"Value\",\"valueType\":\"NUMBER\",\"type\":\"java.lang.Double\",\"hidden\":false,\"meta\":false}],\"metaData\":{\"items\":{\"dx\":{\"name\":\"Data\"},\"pq2XI5kz2BY\":{\"name\":\"Fixed\"},\"pe\":{\"name\":\"Period\"},\"cYeuwXTCPkU\":{\"name\":\"ANC 2nd visit\"},\"ou\":{\"name\":\"Organisation unit\"},\"PT59n8BQbqM\":{\"name\":\"Outreach\"},\"201601\":{\"name\":\"January 2016\"},\"O6uvpzGd5pu\":{\"name\":\"Bo\"},\"fbfJHSPpUQD\":{\"name\":\"ANC 1st visit\"},\"co\":{\"name\":\"Category option combo\"},\"lc3eMKXaEfw\":{\"name\":\"Bonthe\"}},\"dimensions\":{\"dx\":[\"fbfJHSPpUQD\",\"cYeuwXTCPkU\"],\"pe\":[\"201601\"],\"ou\":[\"O6uvpzGd5pu\",\"lc3eMKXaEfw\"],\"co\":[\"pq2XI5kz2BY\",\"PT59n8BQbqM\"]}},\"rows\":[],\"height\":0,\"headerWidth\":5,\"width\":0}"), 
    date = structure(1693921005, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.093267, namelookup = 0.00257, 
    connect = 0.087767, pretransfer = 0.132778, starttransfer = 0.285807, 
    total = 0.285976)), class = "response")
