structure(list(url = "https://play.dhis2.org/40.0.1/api/categoryOptions.json?paging=false&filter=id:in:[NA,FbLZS3ueWbQ,K4gwuiVvW3z]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 14:22:50 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0b006cc0486671c4afc4a779043f2f0e6\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 14:22:49 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/categoryOptions.json?paging=false&filter=id:in:[NA,FbLZS3ueWbQ,K4gwuiVvW3z]&fields=id,name"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 14:22:50 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0b006cc0486671c4afc4a779043f2f0e6\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"categoryOptions\":[{\"name\":\"0-11m\",\"id\":\"FbLZS3ueWbQ\"},{\"name\":\"0-4y\",\"id\":\"K4gwuiVvW3z\"}]}"), 
    date = structure(1693923770, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.057055, namelookup = 0.000108, 
    connect = 0, pretransfer = 0.000294, starttransfer = 0.143642, 
    total = 0.143858)), class = "response")
