structure(list(url = "https://play.dhis2.org/40.0.1/api/dimensions.json?paging=false&filter=id:eq:gtuVl6NbXQV&fields=items[name,id]", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 10:29:35 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0c0261b7977c0e61e806e4fd6eb524370\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 10:29:35 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/dimensions.json?paging=false&filter=id:eq:gtuVl6NbXQV&fields=items[name,id]"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 10:29:35 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0c0261b7977c0e61e806e4fd6eb524370\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"dimensions\":[{\"items\":[{\"name\":\"Consumption\",\"id\":\"AdkHQiiJBB4\"},{\"name\":\"End Balance\",\"id\":\"xp1wtEkhBmV\"},{\"name\":\"Quantity to be ordered\",\"id\":\"gpK9r0M1RFZ\"}]}]}"), 
    date = structure(1693909775, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.043517, namelookup = 7.9e-05, 
    connect = 0, pretransfer = 0.000244, starttransfer = 0.096009, 
    total = 0.096166)), class = "response")
