structure(list(url = "https://play.dhis2.org/40.0.1/api/me.json?paging=false&fields=name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 11:49:21 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        etag = "W/\"09eeb19a48f9653c566240ab88ccb29ed\"", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 11:49:20 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/me.json?paging=false&fields=name"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 11:49:21 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        etag = "W/\"09eeb19a48f9653c566240ab88ccb29ed\"", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"name\":\"John Traore\"}"), 
    date = structure(1693914561, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.048672, namelookup = 7.6e-05, 
    connect = 0, pretransfer = 0.000276, starttransfer = 0.108161, 
    total = 0.108322)), class = "response")
