structure(list(url = "https://play.dhis2.org/40.0.1/api/optionGroups.json?paging=false&filter=id:in:[hTDovVfKAuN]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 13:15:38 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-length` = "19", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "\"015b63cd55676e9250e7182c7ea1e2391\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 13:15:38 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/optionGroups.json?paging=false&filter=id:in:[hTDovVfKAuN]&fields=id,name"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 13:15:38 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-length` = "19", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "\"015b63cd55676e9250e7182c7ea1e2391\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"optionGroups\":[]}"), 
    date = structure(1693919738, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.045922, namelookup = 8e-05, 
    connect = 0, pretransfer = 0.000248, starttransfer = 0.10925, 
    total = 0.10934)), class = "response")
