structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=organisationUnitGroups[name,id],ancestors[name,id]", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 13:27:27 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0038352dacfb1fd2976de56fc961278d8\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 13:27:27 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=organisationUnitGroups[name,id],ancestors[name,id]"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 13:27:27 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0038352dacfb1fd2976de56fc961278d8\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"organisationUnitGroups\":[{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"}],\"ancestors\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\"},{\"name\":\"Western Area\",\"id\":\"at6UHUQatSo\"},{\"name\":\"Rural Western Area\",\"id\":\"qtr8GGlm4gg\"}]},{\"organisationUnitGroups\":[{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"},{\"name\":\"Clinic\",\"id\":\"RXL3lPSK8oG\"}],\"ancestors\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\"},{\"name\":\"Western Area\",\"id\":\"at6UHUQatSo\"},{\"name\":\"Rural Western Area\",\"id\":\"qtr8GGlm4gg\"}]}]}"), 
    date = structure(1693920447, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.044493, namelookup = 0.000139, 
    connect = 0, pretransfer = 0.000285, starttransfer = 0.107885, 
    total = 0.10799)), class = "response")
