structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnits.json?paging=false&filter=name:like:Baoma&fields=name,id", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 10:29:42 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0643df7cc7e37d435e0334d85694b1f89\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 10:29:41 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnits.json?paging=false&filter=name:like:Baoma&fields=name,id"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 10:29:42 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0643df7cc7e37d435e0334d85694b1f89\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"name\":\"Baoma\",\"id\":\"vWbkYPRmKyS\"},{\"name\":\"Baomahun CHC\",\"id\":\"FLjwMPWLrL2\"},{\"name\":\"Baoma (Koya) CHC\",\"id\":\"Yj2ni275yPJ\"},{\"name\":\"Baoma Kpenge CHP\",\"id\":\"a1dP5m3Clw4\"},{\"name\":\"Baoma (Luawa) MCHP\",\"id\":\"TQ5DSmdliN7\"},{\"name\":\"Baoma MCHP\",\"id\":\"t52CJEyLhch\"},{\"name\":\"Baoma Oil Mill CHC\",\"id\":\"Y8foq27WLti\"},{\"name\":\"Baoma-Peje CHP\",\"id\":\"x8SUTSsJoeO\"},{\"name\":\"Baoma Station CHP\",\"id\":\"jNb63DIHuwU\"},{\"name\":\"Pelewahun (Baoma) MCHP\",\"id\":\"KfUCAQoOIae\"}]}"), 
    date = structure(1693909782, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.043144, namelookup = 8e-05, 
    connect = 0, pretransfer = 0.000242, starttransfer = 0.100682, 
    total = 0.100848)), class = "response")
