structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&filter=name:in:[Country]&fields=name,organisationUnits[id,name,level,ancestors[id,name]]", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 13:07:26 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"08899a8393df1dbb52fb0fe342bd9ee9c\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 13:07:26 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&filter=name:in:[Country]&fields=name,organisationUnits[id,name,level,ancestors[id,name]]"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 13:07:26 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"08899a8393df1dbb52fb0fe342bd9ee9c\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"Country\",\"organisationUnits\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\",\"level\":1,\"ancestors\":[]}]}]}"), 
    date = structure(1693919246, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.093289, namelookup = 0.009221, 
    connect = 0.095758, pretransfer = 0.142741, starttransfer = 0.256638, 
    total = 0.256797)), class = "response")
