structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&fields=name,id", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 10:29:38 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"05c971d1e665f8c65b7cd0ca38a2b65c8\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 10:29:38 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&fields=name,id"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 10:29:38 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"05c971d1e665f8c65b7cd0ca38a2b65c8\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"CHC\",\"id\":\"CXw2yu5fodb\"},{\"name\":\"Chiefdom\",\"id\":\"gzcv65VyaGq\"},{\"name\":\"CHP\",\"id\":\"uYxK4wmcPqA\"},{\"name\":\"Clinic\",\"id\":\"RXL3lPSK8oG\"},{\"name\":\"Country\",\"id\":\"RpbiCJpIYEj\"},{\"name\":\"District\",\"id\":\"w1Atoz18PCL\"},{\"name\":\"Eastern Area\",\"id\":\"nlX2VoouN63\"},{\"name\":\"Hospital\",\"id\":\"tDZVQ1WtwpA\"},{\"name\":\"MCHP\",\"id\":\"EYbopBOJWsW\"},{\"name\":\"Mission\",\"id\":\"w0gFTTmsUcF\"},{\"name\":\"NGO\",\"id\":\"PVLOW4bCshG\"},{\"name\":\"Northern Area\",\"id\":\"J40PpdN4Wkk\"},{\"name\":\"Private Clinic\",\"id\":\"MAs88nJc9nL\"},{\"name\":\"Public facilities\",\"id\":\"oRVt7g429ZO\"},{\"name\":\"Rural\",\"id\":\"GGghZsfu7qV\"},{\"name\":\"Southern Area\",\"id\":\"jqBqIXoXpfy\"},{\"name\":\"Urban\",\"id\":\"f25dqv3Y7Z0\"},{\"name\":\"Western Area\",\"id\":\"b0EsAxm8Nge\"}]}"), 
    date = structure(1693909778, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.040188, namelookup = 8.4e-05, 
    connect = 0, pretransfer = 0.000241, starttransfer = 0.096986, 
    total = 0.097136)), class = "response")
