structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnits.json?paging=false&filter=organisationUnitGroups.name:eq:District&filter=children.id:in:[YuQRtpLP10I,fwH9ipvXde9]&fields=id,name,level,ancestors[id,name]", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 10:29:41 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0a5e83a7d2f6178defae1b5f683ffc216\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 10:29:41 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnits.json?paging=false&filter=organisationUnitGroups.name:eq:District&filter=children.id:in:[YuQRtpLP10I,fwH9ipvXde9]&fields=id,name,level,ancestors[id,name]"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 10:29:41 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"0a5e83a7d2f6178defae1b5f683ffc216\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"name\":\"Bo\",\"id\":\"O6uvpzGd5pu\",\"level\":2,\"ancestors\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\"}]},{\"name\":\"Bombali\",\"id\":\"fdc6uOvgoji\",\"level\":2,\"ancestors\":[{\"name\":\"Sierra Leone\",\"id\":\"ImspTQPwCqd\"}]}]}"), 
    date = structure(1693909781, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.039343, namelookup = 5.7e-05, 
    connect = 0, pretransfer = 0.000181, starttransfer = 0.165719, 
    total = 0.16584)), class = "response")
