structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnitGroupSets.json?paging=false&fields=organisationUnitGroups[name]", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 10:29:39 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"06221fda9f61aee12aa217e3c7751d300\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 10:29:39 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnitGroupSets.json?paging=false&fields=organisationUnitGroups[name]"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 10:29:39 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"06221fda9f61aee12aa217e3c7751d300\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroupSets\":[{\"organisationUnitGroups\":[{\"name\":\"Northern Area\"},{\"name\":\"Southern Area\"},{\"name\":\"Western Area\"},{\"name\":\"Eastern Area\"}]},{\"organisationUnitGroups\":[{\"name\":\"Private Clinic\"},{\"name\":\"NGO\"},{\"name\":\"Mission\"},{\"name\":\"Public facilities\"}]},{\"organisationUnitGroups\":[{\"name\":\"CHC\"},{\"name\":\"Hospital\"},{\"name\":\"Clinic\"},{\"name\":\"CHP\"},{\"name\":\"MCHP\"}]},{\"organisationUnitGroups\":[{\"name\":\"Rural\"},{\"name\":\"Urban\"}]}]}"), 
    date = structure(1693909779, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.038649, namelookup = 5.6e-05, 
    connect = 0, pretransfer = 0.000188, starttransfer = 0.102325, 
    total = 0.102436)), class = "response")
