structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&fields=name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 10:29:39 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"01d48ded437add8c8055f6a2f32115e05\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 10:29:39 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&fields=name"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 10:29:39 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"01d48ded437add8c8055f6a2f32115e05\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"name\":\"CHC\"},{\"name\":\"Chiefdom\"},{\"name\":\"CHP\"},{\"name\":\"Clinic\"},{\"name\":\"Country\"},{\"name\":\"District\"},{\"name\":\"Eastern Area\"},{\"name\":\"Hospital\"},{\"name\":\"MCHP\"},{\"name\":\"Mission\"},{\"name\":\"NGO\"},{\"name\":\"Northern Area\"},{\"name\":\"Private Clinic\"},{\"name\":\"Public facilities\"},{\"name\":\"Rural\"},{\"name\":\"Southern Area\"},{\"name\":\"Urban\"},{\"name\":\"Western Area\"}]}"), 
    date = structure(1693909779, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.040513, namelookup = 5.3e-05, 
    connect = 0, pretransfer = 0.000169, starttransfer = 0.087662, 
    total = 0.087764)), class = "response")
