structure(list(url = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&filter=name:in:[CHP,Rural]&fields=name,id,code", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 10:39:54 GMT", `content-type` = "application/json;charset=UTF-8", 
        `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"08624c6d64d6e37f6aa2106524e8ac59b\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 10:39:54 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/40.0.1/api/organisationUnitGroups.json?paging=false&filter=name:in:[CHP,Rural]&fields=name,id,code"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 10:39:54 GMT", 
        `content-type` = "application/json;charset=UTF-8", `content-security-policy` = "frame-ancestors 'self' http://localhost:8083 http://localhost:8080 http://localhost:8082 http://localhost:8081 https://dhis2.stoplight.io http://localhost:3000 http://localhost:9000;", 
        `cache-control` = "no-cache, private", etag = "W/\"08624c6d64d6e37f6aa2106524e8ac59b\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/40.0.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"organisationUnitGroups\":[{\"code\":\"CHP\",\"name\":\"CHP\",\"id\":\"uYxK4wmcPqA\"},{\"name\":\"Rural\",\"id\":\"GGghZsfu7qV\"}]}"), 
    date = structure(1693910394, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.052669, namelookup = 8.1e-05, 
    connect = 0, pretransfer = 0.000241, starttransfer = 0.111303, 
    total = 0.11143)), class = "response")
