structure(list(url = "https://play.dhis2.org/2.37.10/api/sqlViews.json?paging=false", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 15:28:06 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"0fd3c780b243b567fe9dc81dc8ed46f2b\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 15:28:06 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.37.10/api/sqlViews.json?paging=false"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 15:28:06 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "no-cache, private", 
        etag = "W/\"0fd3c780b243b567fe9dc81dc8ed46f2b\"", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.37.10", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"sqlViews\":[{\"id\":\"QAlOivHBY3a\",\"displayName\":\"Category option combo overview\"},{\"id\":\"YOaOY605rzh\",\"displayName\":\"Code list category option combos\"},{\"id\":\"GCZ01m3pIRd\",\"displayName\":\"Code list data elements\"},{\"id\":\"cOfhJIFGqhP\",\"displayName\":\"Code list data sets\"},{\"id\":\"w3UxFykyHFy\",\"displayName\":\"Code list organisation units\"},{\"id\":\"qMYMT0iUGkG\",\"displayName\":\"Data element by value type\"},{\"id\":\"tw3A6ZXOdbA\",\"displayName\":\"Data elements\"},{\"id\":\"NdbAwXmwE8N\",\"displayName\":\"Data set approval\"},{\"id\":\"ITDzVWfa8DN\",\"displayName\":\"Datavalue\"},{\"id\":\"dI68mLkP1wN\",\"displayName\":\"Facility Overview\"}]}"), 
    date = structure(1693927686, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.050674, namelookup = 6.1e-05, 
    connect = 0, pretransfer = 0.000184, starttransfer = 0.113958, 
    total = 0.114084)), class = "response")
