structure(list(url = "https://play.dhis2.org/2.37.10/api/sqlViews/QAlOivHBY3a/data.json?paging=false&filter=categoryoptioncomboid:eq:1", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Tue, 05 Sep 2023 15:28:10 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "max-age=1209600, public", etag = "W/\"0ea1fbc345fbcbb59e849a34e4854f68e\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx", date = "Tue, 05 Sep 2023 15:28:10 GMT", 
            `content-type` = "text/html", `content-length` = "162", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.37.10/api/sqlViews/QAlOivHBY3a/data.json?paging=false&filter=categoryoptioncomboid:eq:1"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        server = "nginx", date = "Tue, 05 Sep 2023 15:28:10 GMT", 
        `content-type` = "application/json;charset=UTF-8", `cache-control` = "max-age=1209600, public", 
        etag = "W/\"0ea1fbc345fbcbb59e849a34e4854f68e\"", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.37.10", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"listGrid\":{\"title\":\"Category option combo overview\",\"subtitle\":\"Category option combo overview\",\"headers\":[{\"name\":\"categoryoptioncomboid\",\"column\":\"categoryoptioncomboid\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":false},{\"name\":\"categoryoptioncomboname\",\"column\":\"categoryoptioncomboname\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":false},{\"name\":\"approvallevel\",\"column\":\"approvallevel\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":false},{\"name\":\"startdate\",\"column\":\"startdate\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":false},{\"name\":\"enddate\",\"column\":\"enddate\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":false},{\"name\":\"uid\",\"column\":\"uid\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":false}],\"metaData\":{},\"width\":0,\"rows\":[],\"height\":0,\"headerWidth\":6}}"), 
    date = structure(1693927690, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.049604, namelookup = 8.8e-05, 
    connect = 0, pretransfer = 0.000249, starttransfer = 0.212404, 
    total = 1.368977)), class = "response")
