structure(list(url = "https://test.datim.org/api/userGroups.json?paging=false&filter=id:in:[M9Uer9SioL7,zpgv1M2Li1Q,seh1e61fwp1,XgctRYBpSiR,TRBfaInIiOK]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Thu, 03 Mar 2022 22:45:43 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"03b9dd5ba3c0e04c340dbc219be837ba4\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Thu, 03 Mar 2022 22:45:43 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", etag = "W/\"03b9dd5ba3c0e04c340dbc219be837ba4\"", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
            `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_test.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"userGroups\":[{\"name\":\"Data ER access\",\"id\":\"M9Uer9SioL7\"},{\"name\":\"Data ER entry\",\"id\":\"XgctRYBpSiR\"},{\"name\":\"Data ESOP access\",\"id\":\"TRBfaInIiOK\"},{\"name\":\"Data HRH access\",\"id\":\"seh1e61fwp1\"},{\"name\":\"OU Cameroon Agency HHS/CDC users\",\"id\":\"zpgv1M2Li1Q\"}]}"), 
    date = structure(1646347543, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4e-05, 
    connect = 4.2e-05, pretransfer = 0.000102, starttransfer = 0.056681, 
    total = 0.056727)), class = "response")
