structure(list(url = "https://test.datim.org/api/userGroups.json?paging=false&filter=id:in:[seh1e61fwp1,c6hGi8GEZot,M9Uer9SioL7,gh9tn4QBbKZ,CwFniyubXbx,OoiLAfMTyMx,iuD8wUFz95X,ik8m9tx6QEw,TRBfaInIiOK,SBtczqnORYA]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Mon, 14 Feb 2022 16:57:57 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"0d742cb8c9f97a1958904e684452feaee\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Mon, 14 Feb 2022 16:57:57 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", etag = "W/\"0d742cb8c9f97a1958904e684452feaee\"", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
            `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_test.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"userGroups\":[{\"name\":\"Data ER access\",\"id\":\"M9Uer9SioL7\"},{\"name\":\"Data ER admin\",\"id\":\"SBtczqnORYA\"},{\"name\":\"Data ESOP access\",\"id\":\"TRBfaInIiOK\"},{\"name\":\"Data HRH access\",\"id\":\"seh1e61fwp1\"},{\"name\":\"Data HRH admin\",\"id\":\"ik8m9tx6QEw\"},{\"name\":\"Data MER access\",\"id\":\"c6hGi8GEZot\"},{\"name\":\"Data MOH access\",\"id\":\"OoiLAfMTyMx\"},{\"name\":\"Data SaSR access\",\"id\":\"CwFniyubXbx\"},{\"name\":\"Data SIMS access\",\"id\":\"iuD8wUFz95X\"},{\"name\":\"Global users\",\"id\":\"gh9tn4QBbKZ\"}]}"), 
    date = structure(1644857877, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.6e-05, 
    connect = 3.7e-05, pretransfer = 9.6e-05, starttransfer = 0.059701, 
    total = 0.06008)), class = "response")
