structure(list(url = "https://test.datim.org/api/userGroups.json?paging=false&filter=id:in:[d3E1aOVZZkZ,M9Uer9SioL7,e1HnTm7vg38,tTSFg9jRcIB,seh1e61fwp1,TRBfaInIiOK,zZ711zXQxw8,c6hGi8GEZot]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Mon, 14 Feb 2022 16:57:58 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"0a3cc75485759de64d51b5be7cc06378c\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Mon, 14 Feb 2022 16:57:58 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", etag = "W/\"0a3cc75485759de64d51b5be7cc06378c\"", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
            `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_test.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"userGroups\":[{\"name\":\"Data DHI access\",\"id\":\"zZ711zXQxw8\"},{\"name\":\"Data ER access\",\"id\":\"M9Uer9SioL7\"},{\"name\":\"Data ESOP access\",\"id\":\"TRBfaInIiOK\"},{\"name\":\"Data HRH access\",\"id\":\"seh1e61fwp1\"},{\"name\":\"Data MCAE access\",\"id\":\"d3E1aOVZZkZ\"},{\"name\":\"Data MER access\",\"id\":\"c6hGi8GEZot\"},{\"name\":\"Global Partner 618022149 user administrators - JHPIEGO CORPORATION\",\"id\":\"e1HnTm7vg38\"},{\"name\":\"Global Partner 618022149 users - JHPIEGO CORPORATION\",\"id\":\"tTSFg9jRcIB\"}]}"), 
    date = structure(1644857878, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.2e-05, 
    connect = 3.3e-05, pretransfer = 9.6e-05, starttransfer = 0.027314, 
    total = 0.027396)), class = "response")
