structure(list(url = "https://test.datim.org/api/userGroups.json?paging=false&filter=id:in:[M9Uer9SioL7,seh1e61fwp1,G1O0MJgw8rs,XgctRYBpSiR,TRBfaInIiOK]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Mon, 14 Feb 2022 16:57:57 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"0dcc3bf2cb4cc396322008aa72f8ee06c\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Mon, 14 Feb 2022 16:57:57 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", etag = "W/\"0dcc3bf2cb4cc396322008aa72f8ee06c\"", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
            `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_test.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"userGroups\":[{\"name\":\"Data ER access\",\"id\":\"M9Uer9SioL7\"},{\"name\":\"Data ER entry\",\"id\":\"XgctRYBpSiR\"},{\"name\":\"Data ESOP access\",\"id\":\"TRBfaInIiOK\"},{\"name\":\"Data HRH access\",\"id\":\"seh1e61fwp1\"},{\"name\":\"Global Agency USAID users\",\"id\":\"G1O0MJgw8rs\"}]}"), 
    date = structure(1644857877, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3e-05, 
    connect = 3.2e-05, pretransfer = 8.8e-05, starttransfer = 0.025763, 
    total = 0.025823)), class = "response")
