structure(list(url = "https://test.datim.org/api/userGroups.json?paging=false&filter=id:in:[zZ711zXQxw8]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Mon, 14 Feb 2022 16:57:59 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"0fbdb198f1dfbb635d20a59395e181ed5\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Mon, 14 Feb 2022 16:57:59 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", etag = "W/\"0fbdb198f1dfbb635d20a59395e181ed5\"", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
            `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_test.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"userGroups\":[{\"name\":\"Data DHI access\",\"id\":\"zZ711zXQxw8\"}]}"), 
    date = structure(1644857879, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.4e-05, 
    connect = 2.5e-05, pretransfer = 7.6e-05, starttransfer = 0.026214, 
    total = 0.026274)), class = "response")
