structure(list(url = "https://test.datim.org/api/userGroups.json?paging=false&filter=id:in:[o8ap0XE01bh,c6hGi8GEZot,zY2t7de7Jzz,TRBfaInIiOK]&fields=id,name", 
    status_code = 200L, headers = structure(list(server = "nginx", 
        date = "Mon, 14 Feb 2022 16:57:57 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", etag = "W/\"099a995fbe39fb24f48dc135ffba21e13\"", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Mon, 14 Feb 2022 16:57:57 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", etag = "W/\"099a995fbe39fb24f48dc135ffba21e13\"", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-frame-options` = "SAMEORIGIN", 
            `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_test.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"userGroups\":[{\"name\":\"Data ESOP access\",\"id\":\"TRBfaInIiOK\"},{\"name\":\"Data MER access\",\"id\":\"c6hGi8GEZot\"},{\"name\":\"Data MER Interagency entry\",\"id\":\"zY2t7de7Jzz\"},{\"name\":\"OU South Africa Interagency users\",\"id\":\"o8ap0XE01bh\"}]}"), 
    date = structure(1644857877, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.1e-05, 
    connect = 3.3e-05, pretransfer = 9.5e-05, starttransfer = 0.029896, 
    total = 0.029935)), class = "response")
