structure(list(url = "https://play.dhis2.org/2.34.1/api/analytics.json?paging=false&dimension=dx:v27b2y9kKh7;vEBapQFZ1AA;DwEVHQvMnDZ&dimension=pe:THIS_YEAR&filter=ou:ImspTQPwCqd&displayProperty=NAME&outputIdScheme=UID", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Tue, 06 Oct 2020 05:13:15 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"09b043a88de0af888dcffe0370d53da00\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Tue, 06 Oct 2020 05:13:15 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"09b043a88de0af888dcffe0370d53da00\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.33.6", 
    "/2.34.1"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"headers\":[{\"name\":\"dx\",\"column\":\"Data\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"pe\",\"column\":\"Period\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"value\",\"column\":\"Value\",\"valueType\":\"NUMBER\",\"type\":\"java.lang.Double\",\"hidden\":false,\"meta\":false}],\"metaData\":{\"items\":{\"ImspTQPwCqd\":{\"name\":\"Sierra Leone\"},\"dx\":{\"name\":\"Data\"},\"pe\":{\"name\":\"Period\"},\"DwEVHQvMnDZ\":{\"name\":\"Public facilities with access to stable electrical power\"},\"ou\":{\"name\":\"Organisation unit\"},\"THIS_YEAR\":{\"name\":\"This year\"},\"v27b2y9kKh7\":{\"name\":\"Public facilities with access to Internet connectivity\"},\"2020\":{\"name\":\"2020\"},\"vEBapQFZ1AA\":{\"name\":\"Public facilities with access to running water\"}},\"dimensions\":{\"dx\":[\"v27b2y9kKh7\",\"vEBapQFZ1AA\",\"DwEVHQvMnDZ\"],\"pe\":[\"2020\"],\"ou\":[\"ImspTQPwCqd\"],\"co\":[]}},\"rows\":[[\"v27b2y9kKh7\",\"2020\",\"45.6\"],[\"vEBapQFZ1AA\",\"2020\",\"27.3\"],[\"DwEVHQvMnDZ\",\"2020\",\"36.5\"]],\"height\":3,\"width\":3,\"headerWidth\":3}"), 
    date = structure(1601961195, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.4e-05, 
    connect = 5.6e-05, pretransfer = 0.000147, starttransfer = 0.190123, 
    total = 0.190233)), class = "response")
