structure(list(url = "https://play.dhis2.org/2.34.1/api/analytics.json?paging=false&dimension=dx:Uvn6LCg7dVU;OdiHJayrsKo;sB79w2hiLp8&dimension=pe:THIS_YEAR&dimension=ou:ImspTQPwCqd&displayProperty=NAME&outputIdScheme=UID", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Thu, 10 Sep 2020 17:35:25 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"035c908986def64bfb9e1a59bb863f314\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Thu, 10 Sep 2020 17:35:25 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"035c908986def64bfb9e1a59bb863f314\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.34.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"headers\":[{\"name\":\"dx\",\"column\":\"Data\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"pe\",\"column\":\"Period\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"ou\",\"column\":\"Organisation unit\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"value\",\"column\":\"Value\",\"valueType\":\"NUMBER\",\"type\":\"java.lang.Double\",\"hidden\":false,\"meta\":false}],\"metaData\":{\"items\":{\"ImspTQPwCqd\":{\"name\":\"Sierra Leone\"},\"sB79w2hiLp8\":{\"name\":\"ANC 3 Coverage\"},\"dx\":{\"name\":\"Data\"},\"pe\":{\"name\":\"Period\"},\"ou\":{\"name\":\"Organisation unit\"},\"Uvn6LCg7dVU\":{\"name\":\"ANC 1 Coverage\"},\"OdiHJayrsKo\":{\"name\":\"ANC 2 Coverage\"},\"THIS_YEAR\":{\"name\":\"This year\"},\"2020\":{\"name\":\"2020\"}},\"dimensions\":{\"dx\":[\"Uvn6LCg7dVU\",\"OdiHJayrsKo\",\"sB79w2hiLp8\"],\"pe\":[\"2020\"],\"ou\":[\"ImspTQPwCqd\"],\"co\":[]}},\"rows\":[[\"Uvn6LCg7dVU\",\"2020\",\"ImspTQPwCqd\",\"103.2\"],[\"OdiHJayrsKo\",\"2020\",\"ImspTQPwCqd\",\"95.4\"],[\"sB79w2hiLp8\",\"2020\",\"ImspTQPwCqd\",\"67.0\"]],\"height\":3,\"width\":4,\"headerWidth\":4}"), 
    date = structure(1599759325, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 8.3e-05, 
    connect = 0.146068, pretransfer = 0.297204, starttransfer = 0.449385, 
    total = 0.449419)), class = "response")
