structure(list(url = "https://play.dhis2.org/2.34.1/api/analytics.json?paging=false&dimension=dx:v27b2y9kKh7;vEBapQFZ1AA;DwEVHQvMnDZ&dimension=pe:THIS_YEAR&displayProperty=NAME&ImspTQPwCqd&outputIdScheme=UID", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Thu, 10 Sep 2020 18:06:50 GMT", `content-type` = "application/json;charset=UTF-8", 
        `set-cookie` = "REDACTED", `cache-control` = "max-age=1209600, public", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "W/\"072af84ed38c382729b722d55daf7bb64\"", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Thu, 10 Sep 2020 18:06:50 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `set-cookie` = "REDACTED", `cache-control` = "max-age=1209600, public", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
            `x-content-type-options` = "nosniff", etag = "W/\"072af84ed38c382729b722d55daf7bb64\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.34.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"headers\":[{\"name\":\"dx\",\"column\":\"Data\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"pe\",\"column\":\"Period\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"value\",\"column\":\"Value\",\"valueType\":\"NUMBER\",\"type\":\"java.lang.Double\",\"hidden\":false,\"meta\":false}],\"metaData\":{\"items\":{\"dx\":{\"name\":\"Data\"},\"pe\":{\"name\":\"Period\"},\"DwEVHQvMnDZ\":{\"name\":\"Public facilities with access to stable electrical power\"},\"THIS_YEAR\":{\"name\":\"This year\"},\"v27b2y9kKh7\":{\"name\":\"Public facilities with access to Internet connectivity\"},\"2020\":{\"name\":\"2020\"},\"vEBapQFZ1AA\":{\"name\":\"Public facilities with access to running water\"}},\"dimensions\":{\"dx\":[\"v27b2y9kKh7\",\"vEBapQFZ1AA\",\"DwEVHQvMnDZ\"],\"pe\":[\"2020\"],\"co\":[]}},\"rows\":[[\"v27b2y9kKh7\",\"2020\",\"45.6\"],[\"vEBapQFZ1AA\",\"2020\",\"27.3\"],[\"DwEVHQvMnDZ\",\"2020\",\"36.5\"]],\"height\":3,\"width\":3,\"headerWidth\":3}"), 
    date = structure(1599761210, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.000115, 
    connect = 0.000124, pretransfer = 0.00054, starttransfer = 0.287111, 
    total = 0.287216)), class = "response")
