structure(list(url = "https://play.dhis2.org/2.34.1/api/organisationUnits.json?paging=false&filter=name:in:[Adonkia%20CHP,Afro%20Arab%20Clinic]&fields=name,organisationUnitGroups[name]", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Tue, 06 Oct 2020 05:13:10 GMT", `content-type` = "application/json;charset=UTF-8", 
        `set-cookie` = "REDACTED", `cache-control` = "no-cache, private", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", etag = "W/\"089654162c953274c31d5cc7ca52af60d\"", 
        `strict-transport-security` = "max-age=15768000", `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Tue, 06 Oct 2020 05:13:10 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `set-cookie` = "REDACTED", `cache-control` = "no-cache, private", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
            `x-content-type-options` = "nosniff", etag = "W/\"089654162c953274c31d5cc7ca52af60d\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.33.6", 
    "/2.34.1"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"organisationUnits\":[{\"name\":\"Adonkia CHP\",\"organisationUnitGroups\":[{\"name\":\"Urban\"}]},{\"name\":\"Afro Arab Clinic\",\"organisationUnitGroups\":[{\"name\":\"Urban\"},{\"name\":\"Clinic\"}]}]}"), 
    date = structure(1601961190, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.6e-05, 
    connect = 3.8e-05, pretransfer = 0.000108, starttransfer = 0.233127, 
    total = 0.23317)), class = "response")
