structure(list(url = "https://play.dhis2.org/2.34.1/api/analytics.json?paging=false&dimension=dx:fbfJHSPpUQD;cYeuwXTCPkU&dimension=pe:201601&dimension=ou:O6uvpzGd5pu;lc3eMKXaEfw&dimension=co&outputIdScheme=UID", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Mon, 14 Sep 2020 19:07:17 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"0c7eb8164d89e9772d5b7bb217ace032e\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Mon, 14 Sep 2020 19:07:17 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"0c7eb8164d89e9772d5b7bb217ace032e\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.34.1", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"headers\":[{\"name\":\"dx\",\"column\":\"Data\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"co\",\"column\":\"Category option combo\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"pe\",\"column\":\"Period\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"ou\",\"column\":\"Organisation unit\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"value\",\"column\":\"Value\",\"valueType\":\"NUMBER\",\"type\":\"java.lang.Double\",\"hidden\":false,\"meta\":false}],\"metaData\":{\"items\":{\"dx\":{\"name\":\"Data\"},\"pq2XI5kz2BY\":{\"name\":\"Fixed\"},\"pe\":{\"name\":\"Period\"},\"cYeuwXTCPkU\":{\"name\":\"ANC 2nd visit\"},\"ou\":{\"name\":\"Organisation unit\"},\"PT59n8BQbqM\":{\"name\":\"Outreach\"},\"201601\":{\"name\":\"January 2016\"},\"O6uvpzGd5pu\":{\"name\":\"Bo\"},\"fbfJHSPpUQD\":{\"name\":\"ANC 1st visit\"},\"co\":{\"name\":\"Category option combo\"},\"lc3eMKXaEfw\":{\"name\":\"Bonthe\"}},\"dimensions\":{\"dx\":[\"fbfJHSPpUQD\",\"cYeuwXTCPkU\"],\"pe\":[\"201601\"],\"ou\":[\"O6uvpzGd5pu\",\"lc3eMKXaEfw\"],\"co\":[\"pq2XI5kz2BY\",\"PT59n8BQbqM\"]}},\"rows\":[],\"height\":0,\"width\":0,\"headerWidth\":5}"), 
    date = structure(1600110437, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.8e-05, 
    connect = 5e-05, pretransfer = 0.000128, starttransfer = 0.16296, 
    total = 0.163049)), class = "response")
