structure(list(url = "https://play.dhis2.org/2.34.1/api/analytics.json?paging=false&dimension=dx:fbfJHSPpUQD&startDate=2019-01-01&endDate=2019-01-01&outputIdScheme=UID", 
    status_code = 200L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Wed, 09 Sep 2020 20:00:52 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
        `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
        etag = "W/\"015a2a858fcd9f00826e43b2a59a93e07\"", `strict-transport-security` = "max-age=15768000", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.17.10", date = "Wed, 09 Sep 2020 20:00:52 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "max-age=1209600, public", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            etag = "W/\"015a2a858fcd9f00826e43b2a59a93e07\"", 
            `strict-transport-security` = "max-age=15768000", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c("#HttpOnly_play.dhis2.org", 
    "#HttpOnly_play.dhis2.org"), flag = c(FALSE, FALSE), path = c("/2.33.6", 
    "/2.34.1"), secure = c(TRUE, TRUE), expiration = structure(c(Inf, 
    Inf), class = c("POSIXct", "POSIXt")), name = c("JSESSIONID", 
    "JSESSIONID"), value = c("REDACTED", "REDACTED")), row.names = c(NA, 
    -2L), class = "data.frame"), content = charToRaw("{\"headers\":[{\"name\":\"dx\",\"column\":\"Data\",\"valueType\":\"TEXT\",\"type\":\"java.lang.String\",\"hidden\":false,\"meta\":true},{\"name\":\"value\",\"column\":\"Value\",\"valueType\":\"NUMBER\",\"type\":\"java.lang.Double\",\"hidden\":false,\"meta\":false}],\"metaData\":{\"items\":{\"dx\":{\"name\":\"Data\"},\"pq2XI5kz2BY\":{\"name\":\"Fixed\"},\"PT59n8BQbqM\":{\"name\":\"Outreach\"},\"fbfJHSPpUQD\":{\"name\":\"ANC 1st visit\"}},\"dimensions\":{\"dx\":[\"fbfJHSPpUQD\"],\"pe\":[],\"co\":[\"pq2XI5kz2BY\",\"PT59n8BQbqM\"]}},\"rows\":[],\"height\":0,\"width\":0,\"headerWidth\":2}"), 
    date = structure(1599681652, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.34404, 
    connect = 0.524734, pretransfer = 0.704952, starttransfer = 0.886441, 
    total = 0.886523)), class = "response")
