structure(list(url = "https://play.dhis2.org/2.33.5/apii/me.json?paging=false", 
    status_code = 404L, headers = structure(list(server = "nginx/1.17.10", 
        date = "Fri, 07 Aug 2020 09:28:53 GMT", `content-type` = "text/html;charset=utf-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", `content-language` = "en", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Fri, 07 Aug 2020 09:28:53 GMT", 
            `content-type` = "text/html", `content-length` = "146", 
            connection = "keep-alive", location = "https://play.dhis2.org/2.33.5/apii/me.json?paging=false", 
            `strict-transport-security` = "max-age=15768000"), class = c("insensitive", 
        "list"))), list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.17.10", date = "Fri, 07 Aug 2020 09:28:53 GMT", 
            `content-type` = "text/html;charset=utf-8", `transfer-encoding` = "chunked", 
            connection = "keep-alive", `x-xss-protection` = "1; mode=block", 
            `x-frame-options` = "SAMEORIGIN", `x-content-type-options` = "nosniff", 
            `content-language` = "en", `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_play.dhis2.org", 
        flag = FALSE, path = "/2.33.5", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;2.33.5&#47;apii&#47;me.json</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.50</h3></body></html>"), 
    date = structure(1596792533, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.222017, namelookup = 4.8e-05, 
    connect = 5.1e-05, pretransfer = 0.000119, starttransfer = 0.038497, 
    total = 0.260583)), class = "response")
