structure(list(url = "https://test.datim.org/api/dataStore/dataQualityTool/foo.json?paging=false", 
    status_code = 404L, headers = structure(list(server = "nginx", 
        date = "Wed, 10 May 2023 04:55:38 GMT", `content-type` = "application/json;charset=UTF-8", 
        `cache-control` = "no-cache, private", `x-content-type-options` = "nosniff", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
        `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
        `content-encoding` = "gzip"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/2", 
        headers = structure(list(server = "nginx", date = "Wed, 10 May 2023 04:55:38 GMT", 
            `content-type` = "application/json;charset=UTF-8", 
            `cache-control` = "no-cache, private", `x-content-type-options` = "nosniff", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "SAMEORIGIN", 
            `strict-transport-security` = "max-age=63072000; includeSubdomains; preload", 
            `content-encoding` = "gzip"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "#HttpOnly_test.datim.org", 
        flag = FALSE, path = "/", secure = TRUE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "JSESSIONID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("{\"httpStatus\":\"Not Found\",\"httpStatusCode\":404,\"status\":\"ERROR\",\"message\":\"Key 'foo' not found in namespace 'dataQualityTool'\"}"), 
    date = structure(1683694538, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.9e-05, 
    connect = 2.9e-05, pretransfer = 0.000105, starttransfer = 0.141035, 
    total = 0.141067)), class = "response")
